### ISSUE TITLE
Neue FacebookGraphException bricht Collectorstart in lookupUser() ab.

### ISSUE THREAD

**Issue by flypsite** [flypsite/general#117]
215 10:11:58.336 Thread-288   ERROR Collector                - problem starting the	 collector
	com.restfb.exception.FacebookGraphException: Received Facebook error response of type GraphMethodException: Unsupported get request. Object with ID 'IT2U.GmbH' does not exist, cannot be loaded due to missing permissions, or does not support this operation. Please read the Graph API documentation at https://developers.facebook.com/docs/graph-api (code 100, subcode null)
		at com.restfb.DefaultFacebookClient$DefaultGraphFacebookExceptionMapper.exceptionForTypeAndMessage(DefaultFacebookClient.java:1203)
		at com.restfb.DefaultFacebookClient.throwFacebookResponseStatusExceptionIfNecessary(DefaultFacebookClient.java:1118)
		at com.restfb.DefaultFacebookClient.makeRequestAndProcessResponse(DefaultFacebookClient.java:1059)
		at com.restfb.DefaultFacebookClient.makeRequest(DefaultFacebookClient.java:970)
		at com.restfb.DefaultFacebookClient.makeRequest(DefaultFacebookClient.java:932)
		at com.restfb.DefaultFacebookClient.fetchObject(DefaultFacebookClient.java:392)
		at tv.flyp.process.resource.FacebookResource.lookupUser(FacebookResource.java:243)
		at tv.flyp.process.resource.FacebookResource$FacebookEntity.<init>(FacebookResource.java:352)
		at tv.flyp.collect.facebook.FacebookSource2.start(FacebookSource2.java:69)
		at tv.flyp.collect.facebook.FacebookCollector2.start(FacebookCollector2.java:212)
		at tv.flyp.collect.Collector.runStart(Collector.java:444)
		at tv.flyp.collect.Collector.access$500(Collector.java:24)
		at tv.flyp.collect.Collector$CollectorCommandRunner.run(Collector.java:310)

**Comment by MeKugel** [comment]
Facebook lieferte (zumindest in diesem Fall) bei einem nicht gefundenen User nicht wie sonst eine OAuth Exception, sondern eine Graph Exception zurück. Dies wurde nicht abgefangen.

Ist im Code gefixt und wird auf dem Developmentsystem getestet
