### ISSUE TITLE
Collector: "falsche" Twitterhandles in der Fehlermeldung anzeigen

### ISSUE THREAD

**Issue by maotv** [flypsite/general#46]
Im Log wird der Userhandle ausgegeben, in der Fehlermeldung auf der Collectorseite nicht.

```
118 15:42:06.172 Thread-278   ERROR TwitterCollector2        - problem creating follow query
twitter4j.TwitterException: Exception while looking up users: antincnukan93
    at tv.flyp.collect2.twitter.TwitterCollector2.lookupUsers(TwitterCollector2.java:967)
    at tv.flyp.collect2.twitter.TwitterCollector2.bootFollow(TwitterCollector2.java:846)
    at tv.flyp.collect2.twitter.TwitterCollector2.configureTwitter(TwitterCollector2.java:334)
    at tv.flyp.collect2.twitter.TwitterCollector2.start(TwitterCollector2.java:120)
    at tv.flyp.collect2.Collector2.runStart(Collector2.java:449)
    at tv.flyp.collect2.Collector2.access$400(Collector2.java:23)
    at tv.flyp.collect2.Collector2$CollectorCommandRunner.run(Collector2.java:305)
Caused by: twitter4j.TwitterException: 404:The URI requested is invalid or the resource requested, such as a user, does not exists. Also returned when the requested format is not supported by the requested method.
message - No user matches for specified terms.
code - 17
```

**Comment by joachimgo** [comment]
siehe #74 und #76
