### ISSUE TITLE
Medienklammer im Publisher: Man kann keine Tagesschau/NDR-Bilder zuweisen

### ISSUE THREAD

**Issue by joachimgo** [flypsite/general#48]
keine Fehler in JavaScript-Console.
Eventhq-Log:

```
127 17:04:10.100 qtp1013261059-41 WARN  Message                  - fixing eventid on user 0 => [User #0 E1427 www Unknown]
127 17:04:10.100 qtp1013261059-41 ERROR ApiHandler               - 
java.lang.IllegalArgumentException: User has no UUID: [User #0 E1427 www Unknown]
        at tv.flyp.core.Message.setUser(Message.java:286)
        at tv.flyp.process2.PageAnalyzer2.updateMessage2(PageAnalyzer2.java:222)
        at tv.flyp.process.resource.TagesschauResource.buildMessage(TagesschauResource.java:47)
        at tv.flyp.process.Resource.buildMessage(Resource.java:136)
        at tv.flyp.process.MessageBuilder2.buildMessageFromUrl(MessageBuilder2.java:75)
        at tv.flyp.process.MessageBuilder2.buildMediaFromUrl(MessageBuilder2.java:83)
        at tv.flyp.api.ApiHandler.appendNewMediaFromURLToMessage(ApiHandler.java:561)
        at tv.flyp.api.handler.MessageHandler.apiMessageNewmedia(MessageHandler.java:226)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:497)
        at tv.flyp.api.ApiHandler.invokeWithInstance(ApiHandler.java:327)
        at tv.flyp.api.ApiHandler.handleRequest(ApiHandler.java:272)
        at tv.flyp.api.ApiDaemon.processRequest(ApiDaemon.java:959)
        at tv.flyp.api.ApiDaemon$ApiServlet.service(ApiDaemon.java:474)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
        at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:711)
        at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:552)
        at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:481)
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
        at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97)
        at org.eclipse.jetty.server.Server.handle(Server.java:462)
        at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:281)
        at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:232)
        at org.eclipse.jetty.io.AbstractConnection$1.run(AbstractConnection.java:505)
        at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:607)
        at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:536)
        at java.lang.Thread.run(Thread.java:745)
```

**Comment by maotv** [comment]
Ein direkter Link auf ein Bild auf tagesschau.de läuft in die TagesschauResource, die ist aber darauf nicht vorbereitet. Temporärer Fix: 
return uri.getHost().contains("tagesschau.de") && ! uri.toString.endsWith(".jpg");

**Comment by joachimgo** [comment]
NEIN, das Problem ist jedes Bild. Ich habe nur mit tagesschau-Bildern getestet.

**Comment by maotv** [comment]
Selbes problem bei ndr.de, selben fix eingebaut

**Comment by MeKugel** [comment]
gefixt
