### ISSUE TITLE
Instagram-Fehler im Flyp-Backend nicht nachvolliziehbar

### ISSUE THREAD

**Issue by joachimgo** [flypsite/general#52]
Collector #5427 im Event #954 liefert im Backend den Fehler "Initialize Error" für die Hashtags #EineStadtEinZiel, #3liga, #sflotte.

Im Log wird folgender Fehler ausgegeben:
    144 18:53:19.984 Thread-980   ERROR InstagramSource2         - C5427/S20159: Initialize Error
    org.jinstagram.exceptions.InstagramException: initial scrape fails
            at tv.flyp.collect2.instagram.InstagramScraper.init(InstagramScraper.java:86)
            at tv.flyp.collect2.instagram.InstagramScraper.<init>(InstagramScraper.java:57)
            at tv.flyp.collect2.instagram.InstagramSource2.start(InstagramSource2.java:105)
            at tv.flyp.collect2.instagram.InstagramCollector2.start(InstagramCollector2.java:101)
            at tv.flyp.collect2.Collector2.runStart(Collector2.java:452)
            at tv.flyp.collect2.Collector2.access$400(Collector2.java:23)
            at tv.flyp.collect2.Collector2$CollectorCommandRunner.run(Collector2.java:308)
    Caused by: org.jinstagram.exceptions.InstagramException: Unknown error response code: 404 <!DOCTYPE html>

In beiden Fällen ist nicht klar, auf was (welchen Hashtag) sich die Meldung bezieht.
Im Log wird außerdem die ganze Fehlerseite ausgegeben, was definitiv nicht zur Lesbarkeit beiträgt.

**Comment by joachimgo** [comment]
Source gelöscht und neu angelegt. Dann ist gut
