### ISSUE TITLE
Instagram-Collector: Fehlermeldungen aus Sources werden nicht angezeigt

### ISSUE THREAD

**Issue by joachimgo** [flypsite/general#73]
Fehler in einer Instagram-Source führen zu NullPointer-Exceptions; der Collector startet endlos, es werden keine Fehlermeldungen an die Backend-GUI zurückgemeldet.

Beispielevent: admin/googlealerts

```
201 10:14:08.919 Thread-719   ERROR InstagramSource2         - C9190/S20896: User schmidt1994 cannot be scraped (maybe private profile)
org.jinstagram.exceptions.InstagramBadRequestException: APINotAllowedError: you cannot view this resource
        at org.jinstagram.entity.common.InstagramErrorResponse.throwException(InstagramErrorResponse.java:45)
        at org.jinstagram.Instagram.handleInstagramError(Instagram.java:1187)
        at org.jinstagram.Instagram.createInstagramObject(Instagram.java:1131)
        at org.jinstagram.Instagram.createInstagramObject(Instagram.java:1150)
        at org.jinstagram.Instagram.getRecentMediaFeed(Instagram.java:361)
        at tv.flyp.collect.instagram.InstagramScraper.getMediaFeedData(InstagramScraper.java:151)
        at tv.flyp.collect.instagram.InstagramScraper.scrape(InstagramScraper.java:189)
        at tv.flyp.collect.instagram.InstagramScraper.init(InstagramScraper.java:79)
        at tv.flyp.collect.instagram.InstagramScraper.<init>(InstagramScraper.java:52)
        at tv.flyp.collect.instagram.InstagramSource2.start(InstagramSource2.java:103)
        at tv.flyp.collect.instagram.InstagramCollector2.start(InstagramCollector2.java:103)
        at tv.flyp.collect.Collector.runStart(Collector.java:439)
        at tv.flyp.collect.Collector.access$400(Collector.java:23)
        at tv.flyp.collect.Collector$CollectorCommandRunner.run(Collector.java:304)
201 10:14:08.920 Thread-719   ERROR InstagramSource2         - C9190/S20896: Initialize Error
org.jinstagram.exceptions.InstagramException: initial scrape fails
        at tv.flyp.collect.instagram.InstagramScraper.init(InstagramScraper.java:81)
        at tv.flyp.collect.instagram.InstagramScraper.<init>(InstagramScraper.java:52)
        at tv.flyp.collect.instagram.InstagramSource2.start(InstagramSource2.java:103)
        at tv.flyp.collect.instagram.InstagramCollector2.start(InstagramCollector2.java:103)
        at tv.flyp.collect.Collector.runStart(Collector.java:439)
        at tv.flyp.collect.Collector.access$400(Collector.java:23)
        at tv.flyp.collect.Collector$CollectorCommandRunner.run(Collector.java:304)
Caused by: java.lang.NullPointerException: null
        at tv.flyp.collect.AbstractSource.sendStatusUpdate(AbstractSource.java:248)
        at tv.flyp.collect.AbstractSource.reportError(AbstractSource.java:234)
        at tv.flyp.collect.instagram.InstagramScraper.getMediaFeedData(InstagramScraper.java:156)
        at tv.flyp.collect.instagram.InstagramScraper.scrape(InstagramScraper.java:189)
        at tv.flyp.collect.instagram.InstagramScraper.init(InstagramScraper.java:79)
        ... 6 common frames omitted
201 10:14:08.920 Thread-719   ERROR Collector                - problem starting the      collector
java.lang.NullPointerException: null
        at tv.flyp.collect.AbstractSource.sendStatusUpdate(AbstractSource.java:248)
        at tv.flyp.collect.AbstractSource.reportError(AbstractSource.java:234)
        at tv.flyp.collect.instagram.InstagramSource2.start(InstagramSource2.java:106)
        at tv.flyp.collect.instagram.InstagramCollector2.start(InstagramCollector2.java:103)
        at tv.flyp.collect.Collector.runStart(Collector.java:439)
        at tv.flyp.collect.Collector.access$400(Collector.java:23)
        at tv.flyp.collect.Collector$CollectorCommandRunner.run(Collector.java:304)
```

**Comment by joachimgo** [comment]
gut
